### ISSUE TITLE
decimal places to hundredths?

### ISSUE THREAD

**Issue by derekphilipau** [PieterMostert/Lipgloss#7]
I'm still figuring out Lipgloss, but it would be easier for me to use if there were two decimal places for all fields.  Not sure if that is a simple change or not.

**Comment by PieterMostert** [comment]
It won't be hard to change, but I prefer having only 1 for the ingredients, and 3 for UMF fluxes, so that you have at most 3 significant figures. If you'd like to change it on your local copy, just change the parameter dec_pt = ... to dec_pt = 2 whenever an instance of the Restriction class is defined in section 5 of restrictions.py (there should be 5 such cases).

**Comment by PieterMostert** [comment]
A simpler way to do this would be to set self.dec_pt = 2 in line 48 of restrictions.py
